### ISSUE TITLE
leggi urgente

### ISSUE THREAD

**Issue by Fab10Supremetb** [Shell1010/Bolt-scraper#3]
01110011 01110100 01101111 01100011 01100101 01110010 01100011 01100001 01101110 01110100  01101111 01110100 01100001 01110100  01100001 01101011 01100001 01110011 01101111 01100100i 01101001 01100111 01101100 01101001 01100011 01101000 01100101 01110011 01101111 01101110 01101111 01100110 01100001 01100010 01101001 01101111 01100011 01101111 01101110 01110100  01100001 01110100  01110100  01100001 01101101 01101001 01110001 01110101 01101001 Fab10Supreme#9469 (codice binario perfavore tradurre)

**Comment by Shell1010** [comment]
TU ES MUY FEO
